export const signToEmoticon: Record<string, string> = {
  'curve-right': '↪️',
  'y-intersection': '🚸',
  'no-right-turn': '↪️🚫',
  'narrow-bridge': '🌉',
  'pedestrian': '🚶',
  'parking': '🅿️',
  'construction': '🚧',
  'overtaking': '🚗💨🚫',
  'one-way': '➡️',
  'bicycle': '🚲',
  'winding-road': '🔄',
  'no-entry': '🚫',
  'stop': '🛑',
  'traffic-light': '🚦',
  'road-narrows': '↔️',
  'warning': '⚠️',
  'landslide': '⛰️',
  'curve-left': '↩️',
  'first-aid': '⛑️',
  'slippery': '⚠️',
  'right-turn': '↪️',
  'crossroads': '➕',
  'no-u-turn': '🔄🚫',
  'falling-rocks': '⚠️',
  'give-way': '⬇️',
  'steep-hill': '⛰️',
  'roundabout': '🔁',
  'left-turn': '↩️',
  'pedestrian-crossing': '🚶',
  'no-stopping': '🛑🚫',
  'no-bicycles': '🚲🚫'
};
